-- Migration: Add persoon_types support
-- Purpose: Allow categorizing persons (Klant, Kind, Mediator, etc.)
-- Author: Generated by Claude Code
-- Date: 2025-10-02

-- Step 1: Create persoon_types lookup table
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'persoon_types')
BEGIN
    CREATE TABLE dbo.persoon_types (
        id INT PRIMARY KEY IDENTITY(1,1),
        naam NVARCHAR(50) NOT NULL UNIQUE,
        beschrijving NVARCHAR(255) NULL,
        actief BIT NOT NULL DEFAULT 1,
        aangemaakt_op DATETIME2 NOT NULL DEFAULT GETDATE(),
        gewijzigd_op DATETIME2 NOT NULL DEFAULT GETDATE()
    );

    PRINT 'Created table persoon_types';
END
ELSE
BEGIN
    PRINT 'Table persoon_types already exists';
END
GO

-- Step 2: Insert initial persoon types
IF NOT EXISTS (SELECT * FROM dbo.persoon_types WHERE naam = 'Klant')
BEGIN
    INSERT INTO dbo.persoon_types (naam, beschrijving) VALUES
        ('Klant', 'Partij in het dossier'),
        ('Kind', 'Kind van partijen'),
        ('Mediator', 'Mediator bij het dossier'),
        ('Advocaat', 'Advocaat van een partij'),
        ('Hypotheekadviseur', 'Hypotheekadviseur'),
        ('Accountant', 'Accountant');

    PRINT 'Inserted initial persoon types';
END
ELSE
BEGIN
    PRINT 'Persoon types already exist';
END
GO

-- Step 3: Add persoon_type_id column to personen table
IF NOT EXISTS (
    SELECT * FROM sys.columns
    WHERE object_id = OBJECT_ID('dbo.personen')
    AND name = 'persoon_type_id'
)
BEGIN
    ALTER TABLE dbo.personen
    ADD persoon_type_id INT NULL;

    PRINT 'Added persoon_type_id column to personen table';
END
ELSE
BEGIN
    PRINT 'Column persoon_type_id already exists';
END
GO

-- Step 4: Add foreign key constraint
IF NOT EXISTS (
    SELECT * FROM sys.foreign_keys
    WHERE name = 'FK_personen_persoon_type'
)
BEGIN
    ALTER TABLE dbo.personen
    ADD CONSTRAINT FK_personen_persoon_type
    FOREIGN KEY (persoon_type_id) REFERENCES dbo.persoon_types(id);

    PRINT 'Added foreign key constraint FK_personen_persoon_type';
END
ELSE
BEGIN
    PRINT 'Foreign key FK_personen_persoon_type already exists';
END
GO

-- Step 5: Create index for better query performance
IF NOT EXISTS (
    SELECT * FROM sys.indexes
    WHERE name = 'IX_personen_persoon_type_id'
    AND object_id = OBJECT_ID('dbo.personen')
)
BEGIN
    CREATE INDEX IX_personen_persoon_type_id
    ON dbo.personen(persoon_type_id);

    PRINT 'Created index IX_personen_persoon_type_id';
END
ELSE
BEGIN
    PRINT 'Index IX_personen_persoon_type_id already exists';
END
GO

-- Step 6: Set default values for existing records (optional)
-- You can set existing persons to 'Klant' if needed
-- UPDATE dbo.personen
-- SET persoon_type_id = (SELECT id FROM dbo.persoon_types WHERE naam = 'Klant')
-- WHERE persoon_type_id IS NULL;

PRINT 'Migration completed successfully';
GO
